### ISSUE TITLE
[BUG REPORT]: SERF QPE DSS Records using 9999 instead of -FLT_MAX for missing cell values

### ISSUE THREAD

**Issue by FHanbali** [USACE/cumulus#134]
SERF QPE DSS Records using 9999 instead of -FLT_MAX for missing cell values:
![image](https://user-images.githubusercontent.com/42588801/134261389-98244753-6096-4375-9584-1e48ff2c8f6e.png)

Suspect other SERFC products (QPF) and potentially LMRFC and other product have the same issue as well.

**Comment by jeffsuperglide** [comment]
Issue noticed with MBRFC.  Attempts to replace `9999` with `-FLT_MAX` failed.  `pydsstools` needs investigation how it handles missing values.  Temporarily, zero is used of `9999` for missing QPE in MBRFC.  May need to extend to other QPE grids.  Use of CONUS grids can alleviate this issue until resolved.

**Comment by jeffsuperglide** [comment]
Forked [pydsstools](https://github.com/USACE/pydsstools) repo has Gyanz's updates as branch `2.1`.  Branch `1.6` is at the point his repo was first forked and is still represented in the `develop` branch.  As of his release `v1.7`, the following has been applied

- HEC-DSS 7-IC, released Jan 22, 2021, headers and libraries included
- Setup.py revised to build extension from source code
- Wheel for Windows (Python 3.6 to 3.9) and Ubuntu 20.04 (Python 3.8)

The build from source with the `Setup.py` was failing due to possible file name error.  Issue submitted (https://github.com/gyanz/pydsstools/issues/29).  [USACE/pydsstools 2.1](https://github.com/USACE/pydsstools/tree/2.1) is the updated branch with the filename correction.  Still causing issue as stated in the referenced issue above.
