### ISSUE TITLE
[BUG REPORT]: UI - My Downloads missing after change

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#174]
After changes in https://github.com/USACE/cumulus-ui/pull/83, my_downloads GET request results in 400 error.

@willbreitkreutz 
@brettpalmberg

**Comment by brettpalmberg** [comment]
@willbreitkreutz @adamscarberry - I just self-assigned. Looking at this now.

**Comment by brettpalmberg** [comment]
Result of migrating to `@usace/usace-bundles/create-jwt-api-bundle` (code has been updated since the forked version in cumulus-ui repository).

The newer version of `createJwtApiBundle(config)` accepts a config object.  One of the keys you can put in the config object is `skipTokenConfig: {}`.  skipTokenConfig may have a `custom` property, which is a function that takes `method` and `url` (previously `method` and `path`).

Note: This is the capability that is used in cumulus-ui [here at the time of this issue](https://github.com/USACE/cumulus-ui/blob/develop/src/app-bundles/index.js#L75) (image copied below): 

<img width="643" alt="image" src="https://user-images.githubusercontent.com/29417036/153032617-cfc974f1-8e1e-4b5c-a9bb-efd10bd5ea24.png">

Note: _Docs coming soon._ https://github.com/USACE/usace-bundles/issues/2

@adamscarberry - I'll tag you as a reviewer on USACE/cumulus-ui/pull/86 - please feel free to merge at will.

**Comment by adamscarberry** [comment]
thanks @brettpalmberg   Local testing appears to be working properly again.
