### ISSUE TITLE
[BUG REPORT]: Grids with `No Data` showing `_nullValue` instead of `UNDEFINED_FLOAT`

### ISSUE THREAD

**Issue by jeffsuperglide** [USACE/cumulus#240]
## Describe the bug
DssVue is plotting the `_nullValue` instead of plotting nothing/blank grid cells.  

Grids with no data, all values are `noData`, are not filtering to UNDEFINED_FLOAT.  Results in missing values plotted in DSSVue.  This means the gridded data is actually the `_nullValue (noData)` value.

DssVue displays blanks(white) if the value is UNDEFINED_FLOAT (different than zeros)
GeoTiff allows defining missing values (noData) when you create a geotiff.  
DSS7 allows defining a _nullValue  in the grid structure

## Steps To Reproduce
Reproduce using a GeoTiff with all values as missing (e.g., 999, -999, 9999, etc)

## Expected behavior
Missing value is assigned to DSS SpatialGridStruct -> _nullValue should not plot in DSSVue.

## Actual behavior
Plotting grids in DSSVue plot the `_nullValue` instead of plotting nothing (i.e., _nullValue)

## Screenshots
![image](https://user-images.githubusercontent.com/37386268/182222999-f72ab2f9-2755-4ab1-83a8-833a2c105414.png)

## Additional context
Grid statistics computed as expected with default max, min, and mean values as -2.0E28, 2.0E28, and -3.4028E38 respectfully.  Filtering `_nullValue` on data array to whatever DSSVue defines as `noData` could solve issue.

**Comment by brettpalmberg** [comment]
Hey @ktarbet, @sharkcooper, may we add you to this issue for awareness and coordination?

**Comment by ktarbet** [comment]
Thanks @brettpalmberg .  I'll check-in with @jeffsuperglide today

**Comment by ktarbet** [comment]
if we use gridStructStore->_nullValue = UNDEFINED_FLOAT --  DSSVue shows blanks(white cells )  tool tip shows 'No Data'
if we use gridStructStore->_nullValue = -9999. -- DssVue plots white cells and shows values in tool tip.
if we use gridStructStore->_nullValue = 99999.999 -- DssVue plots black cells . Tool tip shows '100,000'

DSSVue plotting tool is using library/hec-monolith that doesn't appear to , currently, understand user defined _nullValue.

Options.  
  1) try to work on hec-monolith library ( previously known as hec.jar, rma.jar, and friends) to honor _nullValue
  2) make tiffdss smarter, so if ( all data is missing ) then _nullValue  = UNDEFINED_FLOAT.

Option 2 may be easier, and lower risk, since the hec-monlith is used by many applications.

**Comment by brettpalmberg** [comment]
> Option 2 may be easier, and lower risk, since the hec-monlith is used by many applications.

This sounds very reasonable. @jeffsuperglide, you concur with making the relevant changes in tiffdss?

**Comment by jeffsuperglide** [comment]
Changes in `cumulus-api` branch `feature/tiffdss-rangetable-stats` may be the solution.  More testing needed.

**Comment by brettpalmberg** [comment]
Closing; Coordination moved to HydrologicEngineeringCenter/tiffdss#9.
