### ISSUE TITLE
[QA Review]:  Address static code scan analysis

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#371]
- [x] API/Geoproc - Remove any instance of eval() in python code
- [x] UI - remove console.log in download-bundle.js

cc @jeffsuperglide

**Comment by jeffsuperglide** [comment]
# Cumulus-API
# CWE-244 HEAP INSPECTION(2) (GO)

1. async_listener_listener/main.go
   - line 26
   - DBPass string is an attribute to the Go Struct `Config`

2. api/config/config.go
   - line 14
   - DBPass string is an attribute to the Go Struct `Config`

# CWE-94 CODE INJECTION (PYTHON)

1. async_packager/src/cumulus-packager/configurations.py
   - line 70
   - ✅ removed `eval` replacing with ternary operator

2. async_packager/src/cumulus-packager/configurations.py
   - line 64
   - ✅ removed `eval` replacing with ternary operator

3. async_packager/src/cumulus-packager/configurations.py
   - line 29
   - ✅ removed `eval` replacing with ternary operator

# CWE-798 HARDCODED PASSWORD?CREDENTIALS (PYTHON)

1. utils/send_process_msg.py
   -  line 91
   -  Local development testing products to simulate sending a message to the SQS queue for the geoprocessor
   -  Code not used in application

2. utils/send_process_msg.py
   -  line 84
   -  Local development testing products to simulate sending a message to the SQS queue for the geoprocessor
   -  Code not used in application

3. utils/geoprocess_message.py
   -  line 47
   -  Local development testing products to simulate sending a message to the SQS queue for the geoprocessor
   -  Code not used in application

# CWE-400 REGEX DENIAL OF SERVICE (JAVASCRIPT/NODE.JS)

1. docs/async_packager/html/search/worker.js
   - line 62
   - This is search inside an automated documentation tool, not part of Cumulus.  It runs on github pages.

**Comment by jeffsuperglide** [comment]
# Cumulus-geoproc

# CWE-94 CODE INJECTION (PYTHON)

1. src/cumulus-geoproc/configurations.py
   - line 69
   - removed `eval` replacing with ternary operator

2. src/cumulus-geoproc/configurations.py
   - line 63
   - removed `eval` replacing with ternary operator

3. src/cumulus-geoproc/configurations.py
   - line 30
   - removed `eval` replacing with ternary operator

**Comment by adamscarberry** [comment]
# cumulus-ui

## CWE-117: LOG FORGING (1) (JAVASCRIPT /NODE.JS)SI-10: INFORMATION INPUT VALIDATION

1. src/app-bundles/download-bundle.js

   - line 44
   - ✅ removed console.log()
   - this was silly, the request word flagged, but was not a variable

**Comment by willbreitkreutz** [comment]
@adamscarberry @jeffsuperglide this is great, thanks.  I'm adding my response to the ISSO team below, would you mind making sure I'm not misstating anything?  Thanks.


# Cumulus Scan Result Response

## Cumulus-API

### **CWE-244** Medium - Heap Inspection
`async_listener/listener/main.go`
`api/config/config.go`

DB_Pass is pulled from the environment and stored in a Go struct for access by other methods that need to connect to the database.  I suppose we could refactor so that the value is pulled from the env when needed (i.e. when `config.connStr()` is called) but this will require a change in how we approach connection information.  Looking for advice from ISSO on if this is actually a big issue since a heap dump would indicate bigger problems in my opinion.

### **CWE-94** High - Code Injection
`async_packager/src/cumulus_packager/configurations.py`

Addressed by refactor.

### **CWE-798** Medium - Hardcoded Credentials
`utils/send_process_msg.py`
`utils/geoprocess-message.py`

Code in question in `utils/send_process_msg.py`:
```
84 -> mClient = Minio(
    "localhost:9000",
    access_key="AKIAIOSFODNN7EXAMPLE",
    secret_key="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
    secure=False,
)
91 -> bClient = boto3.resource(
    "sqs",
    endpoint_url="http://localhost:9324",
    region_name="elasticmq",
    aws_secret_access_key="x",
    aws_access_key_id="x",
    use_ssl=False,
)
```

Code in question in `utils/geoprocess-message.py`
```
47 -> CLIENT = boto3.resource(
    "sqs",
    endpoint_url="http://localhost:9324",
    region_name="elasticmq",
    aws_secret_access_key="x",
    aws_access_key_id="x",
    use_ssl=False,
)
```

Credentials are for local testing, not actual credentials. Is there a way to flag as not an issue or should we refactor?

### **CWE-400** Medium - Regex Denial of Service (REDOS)
`docs/async_packager/html/search/worker.js`

Non-issue, the value that is sent to the regex is the content of our documentation, not user input. The regular expression is used by a library to index contents and make searchable by a user.  User input is managed by the library to perform searches and is processed to search the index.  Additionally all regular expression searches are performed client side so a invalid user input would only affect that user.

## Cumulus-Geoprocessor

### **CWE-94** High - Code Injection
`src/cumulus_geoproc/configurations.py`

Addressed by refactor.

## Cumulus-UI

### **CWE-117** Low - Log Forging
`src/app-bundles/download-bundle.js`

Addressed by refactor.

**Comment by adamscarberry** [comment]
@willbreitkreutz This all looks correct to me.

**Comment by willbreitkreutz** [comment]
@adamscarberry cool, thanks!
