### ISSUE TITLE
MRMS 1-Hour Archive

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#51]

**Comment by adamscarberry** [comment]
Need source for the archive.

**Comment by brettpalmberg** [comment]
> Need source for the archive.

@FHanbali - can you share a link for the MRMS 1 Hour Archive?

**Comment by FHanbali** [comment]
I've reached out to UCAR's EOL (https://data.eol.ucar.edu/dataset/558.004) to see if they can provide us with direct access to their archives.  Stay tuned.

**Comment by FHanbali** [comment]
Turns out UCAR's archives are pretty limited for MRMS.  Only comprehensive archives of MRMS I'm aware of are available from Iowa State University, starting from November 2014:

https://mesonet.agron.iastate.edu/archive/

Parent Directory for all archives:
https://mtarchive.geol.iastate.edu/

Example pattern of archive folders per yyyy/mm/dd:
https://mtarchive.geol.iastate.edu/2014/11/01/mrms/ncep/RadarOnly_QPE_01H/

**Comment by willbreitkreutz** [comment]
@adamscarberry can this issue be closed?

**Comment by adamscarberry** [comment]
@willbreitkreutz Trying to remember the details.  I think it will require a new product be created in db along with new processor (not same as current processor).  This has been a "nice to have" that we want to accomplish, but other work has take priority.  Hopefully we tackle this once the new corps.cloud version has been released to users and the client tools are all working as designed.

**Comment by brettpalmberg** [comment]
Closing at this time to prioritize other issues. The length of archive for this product is limited and the newer generation MRMS products (v2) are available in Cumulus.
