### ISSUE TITLE
UI: Redesign Product Details Page

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#78]
Redesign product details page to match newer styles of dashboard.  Truncate heatmap container to keep most if not all of the page "[above the fold](https://en.wikipedia.org/wiki/Above_the_fold)".

Proposed before and after (**design is not final**):

![image](https://user-images.githubusercontent.com/46494851/112693627-59832d00-8e57-11eb-9609-cccbe71864c6.png)

**Comment by FHanbali** [comment]
Thx Adam, love the new layout so that majority of info is viewable upfront.  Would be nice to consider adding options to view the heat map on decade by decade aggregated view as well.  More importantly, Brett and I talked about adding a drill down option from the annual/daily heat map to bring up a simple log summary list of missing data time steps.  At any rate, really nice polishing touches you're making!

**Comment by adamscarberry** [comment]
initial redesign is complete.  Additional features and refactoring will follow.
